# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit_activity_log', '0002_auto_20170216_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolkitactivitylog',
            name='hostname',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
