# Generated by Django 2.2 on 2022-06-08 18:52

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit_activity_log', '0003_toolkitactivitylog_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolkitactivitylog',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolkit_activity_log_toolkitactivitylog_last_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='toolkitactivitylog',
            name='last_updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='toolkit_activity_log_toolkitactivitylog_last_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
