# Generated by Django 4.2.14 on 2024-08-05 12:23

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toolkit_activity_log', '0004_auto_20220608_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolkitactivitylog',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_last_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='toolkitactivitylog',
            name='last_updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_last_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
